/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;

/**
 *
 * @author Carlos
 */
public class Tautenticacao extends classes.ModeloJFrame {

    /**
     * Creates new form Tautenticacao
     *
     * @param back_window
     */
    public Tautenticacao(javax.swing.JFrame back_window) {
        super(back_window);
        initComponents();
        alteracoes("AUTENTICAÇÃO");

        // TESTA CONEXAO COM BANCO DE DADOS
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    if (new util.ConnectionFactory().connectionCheck()) {
                        sitacao_conn.setBackground(new Color(38, 150, 0));
                        sitacao_conn.setToolTipText("Conectado ao BD");
                        status_conn.setText("conectado");
                        break;
                    } else {
                        sitacao_conn.setBackground(new Color(150, 0, 0));
                        sitacao_conn.setToolTipText("Não conectado ao BD");
                        status_conn.setText("desconectado");
                        break;
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_usuario = new javax.swing.JTextField();
        label_icone_usuario = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        label_icone_senha = new javax.swing.JLabel();
        btn_acessar = new javax.swing.JButton();
        link_regEmpresa = new javax.swing.JLabel();
        sitacao_conn = new javax.swing.JLabel();
        status_conn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "AUTENTICAÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(41, 38, 32))); // NOI18N

        txt_usuario.setForeground(new java.awt.Color(41, 38, 32));
        txt_usuario.setToolTipText("Usuário");
        txt_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usuarioFocusLost(evt);
            }
        });

        label_icone_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_icone_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_login.png"))); // NOI18N

        txt_senha.setForeground(new java.awt.Color(41, 38, 32));
        txt_senha.setToolTipText("Senha");
        txt_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_senhaFocusLost(evt);
            }
        });

        label_icone_senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_icone_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pass_login.png"))); // NOI18N

        btn_acessar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_acessar.setForeground(new java.awt.Color(41, 38, 32));
        btn_acessar.setText("ACESSAR");
        btn_acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acessarActionPerformed(evt);
            }
        });

        link_regEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        link_regEmpresa.setForeground(new java.awt.Color(41, 38, 32));
        link_regEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        link_regEmpresa.setText("<html>REGISTRAR</html>");
        link_regEmpresa.setToolTipText("Registrar empresa");
        link_regEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        link_regEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_regEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                link_regEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                link_regEmpresaMouseExited(evt);
            }
        });

        sitacao_conn.setBackground(new java.awt.Color(255, 204, 0));
        sitacao_conn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        sitacao_conn.setForeground(new java.awt.Color(41, 38, 32));
        sitacao_conn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sitacao_conn.setToolTipText("Situação da conexão com o banco de dados");
        sitacao_conn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sitacao_conn.setOpaque(true);
        sitacao_conn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sitacao_connMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sitacao_connMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sitacao_connMouseExited(evt);
            }
        });

        status_conn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        status_conn.setForeground(new java.awt.Color(41, 38, 32));
        status_conn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        status_conn.setText("Aguarde...");
        status_conn.setToolTipText("status");
        status_conn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        status_conn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                status_connMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                status_connMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                status_connMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_icone_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_icone_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_acessar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_usuario)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sitacao_conn, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_conn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(link_regEmpresa)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_usuario)
                    .addComponent(label_icone_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_icone_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_acessar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(link_regEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sitacao_conn, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_conn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void link_regEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_regEmpresaMouseClicked
        if(new util.ConnectionFactory().connectionCheck()){
            link_regEmpresa.setText("<html>REGISTRAR</html>");
            dispose();
            new TregistrarEmpresa(this).setVisible(true);
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "Inicialize o MySql para utilizar este conteúdo.", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_link_regEmpresaMouseClicked

    private void link_regEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_regEmpresaMouseEntered
        link_regEmpresa.setText("<html><u>REGISTRAR</u></html>");
    }//GEN-LAST:event_link_regEmpresaMouseEntered

    private void link_regEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_regEmpresaMouseExited
        link_regEmpresa.setText("<html>REGISTRAR</html>");
    }//GEN-LAST:event_link_regEmpresaMouseExited

    private void btn_acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acessarActionPerformed
        // VALIDAR CAMPOS        
        String usuario = txt_usuario.getText();
        String senha = new String(txt_senha.getPassword());
        txt_usuario.setBackground(new Color(255, 255, 255));
        txt_senha.setBackground(new Color(255, 255, 255));
        if (usuario.isEmpty() || usuario.startsWith(" ") || usuario.equals("") || usuario == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Preencha o campo corretamente", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
            txt_usuario.setBackground(new Color(255, 196, 196));
            txt_usuario.requestFocus(true);
            txt_usuario.setText("");
            return;
        }
        if (new String(txt_senha.getPassword()).isEmpty() || new String(txt_senha.getPassword()).startsWith(" ") || new String(txt_senha.getPassword()).equals("") || new String(txt_senha.getPassword()) == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Preencha o campo corretamente", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
            txt_senha.setBackground(new Color(255, 196, 196));
            txt_senha.requestFocus(true);
            txt_senha.setText("");
            return;
        }

        // EFETUAR LOGIN E OS DADOS ESTIVEREM CORRETOS        
        classes.Operador operador = null;
        dao.DAOoperador daoOperador = new dao.DAOoperador();
        operador = daoOperador.buscarOperadorUserPass(usuario, senha);
        if (operador != null) {
            classes.OperadorAutenticado.operadorAutenticado = operador;
            dispose();
            new Tprincipal(null).setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
            txt_usuario.setText("");
            txt_senha.setText("");
            txt_usuario.requestFocus(true);
        }
    }//GEN-LAST:event_btn_acessarActionPerformed

    private void txt_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usuarioFocusLost
        txt_usuario.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txt_usuarioFocusLost

    private void txt_senhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_senhaFocusLost
        txt_senha.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txt_senhaFocusLost

    private void sitacao_connMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sitacao_connMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sitacao_connMouseClicked

    private void sitacao_connMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sitacao_connMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sitacao_connMouseEntered

    private void sitacao_connMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sitacao_connMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sitacao_connMouseExited

    private void status_connMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_status_connMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_status_connMouseClicked

    private void status_connMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_status_connMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_status_connMouseEntered

    private void status_connMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_status_connMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_status_connMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tautenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tautenticacao(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acessar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_icone_senha;
    private javax.swing.JLabel label_icone_usuario;
    private javax.swing.JLabel link_regEmpresa;
    private javax.swing.JLabel sitacao_conn;
    private javax.swing.JLabel status_conn;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
